/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "app.h"

JNIEXPORT jbyteArray JNICALL Java_com_github_wreulicke_FirstTest_copy
  (JNIEnv *env, jobject thisj, jstring srcj)
{
    const char* src = env->GetStringUTFChars(srcj, NULL);
    if (src == NULL) return NULL;
    jsize len = env->GetStringUTFLength(srcj);

    jbyteArray dstj = env->NewByteArray(len);
    if (dstj == NULL) {
        env->ReleaseStringUTFChars(srcj, src);
        return NULL;
    }
    jbyte* dst = env->GetByteArrayElements(dstj, NULL);
    if (dst == NULL) {
        env->ReleaseStringUTFChars(srcj, src);
        return NULL;
    }

    for(int i = 0; i < len; i++){
        dst[i] = src[i];
    }

    env->ReleaseByteArrayElements(dstj, dst, 0);
    env->ReleaseStringUTFChars(srcj, src);

    return dstj;
}