/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_wreulicke_FirstTest */

extern "C" {
/*
 * Class:     com_github_wreulicke_FirstTest
 * Method:    copy
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_github_wreulicke_FirstTest_copy
  (JNIEnv *, jobject, jstring);

}